export const DEMO_PROJECTS = [
  {
    code: "NH44-P2-2026",
    name: "NH-44 Highway Expansion — Phase 2",
    state: "Karnataka",
    district: "Belagavi",
  },
  {
    code: "EFC-LP-2026",
    name: "Eastern Freight Corridor — Land Parcel Acquisition",
    state: "Bihar",
    district: "Patna",
  },
];

export const DEMO_ACCOUNTS = [
  // ── Executive & System Administration ──
  {
    projectCode: "ALL",
    projectName: "National Mission Control",
    role: "Administrator",
    label: "System Administrator",
    badge: "Super Admin",
    email: "admin@landacquisition.gov.in",
    password: "Admin@2026Secure!",
    departmentName: "All Departments",
    icon: "ShieldAlert",
    color: "from-blue-600 to-indigo-700",
    pillBg: "bg-blue-50 text-blue-700 border-blue-200",
    desc: "Full access to national overview, all projects, creation, deletion & system settings.",
    requiresProject: false,
  },
  {
    projectCode: "ALL",
    projectName: "National Mission Control",
    role: "SeniorOfficer",
    label: "Senior Officer",
    badge: "Executive",
    email: "senior@landacquisition.gov.in",
    password: "Senior@2026Officer!",
    departmentName: "National Oversight",
    icon: "Landmark",
    color: "from-purple-600 to-indigo-700",
    pillBg: "bg-purple-50 text-purple-700 border-purple-200",
    desc: "Executive view: GIS tracking, weighted progress, bottleneck ranking & dependency alerts.",
    requiresProject: false,
  },

  // ── Project 1: NH-44 Highway Expansion (Karnataka) ──
  {
    projectCode: "NH44-P2-2026",
    projectName: "NH-44 Highway Expansion",
    role: "DepartmentOfficer",
    label: "Survey Officer (NH-44)",
    badge: "Survey · 15%",
    email: "survey@landacquisition.gov.in",
    password: "Survey@2026Land!",
    departmentName: "Survey",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "MapPin",
    color: "from-emerald-600 to-teal-700",
    pillBg: "bg-emerald-50 text-emerald-700 border-emerald-200",
  },
  {
    projectCode: "NH44-P2-2026",
    projectName: "NH-44 Highway Expansion",
    role: "DepartmentOfficer",
    label: "Legal Officer (NH-44)",
    badge: "Legal · 15%",
    email: "legal@landacquisition.gov.in",
    password: "Legal@2026Verify!",
    departmentName: "Legal Verification",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "Scale",
    color: "from-cyan-600 to-blue-700",
    pillBg: "bg-cyan-50 text-cyan-700 border-cyan-200",
  },
  {
    projectCode: "NH44-P2-2026",
    projectName: "NH-44 Highway Expansion",
    role: "DepartmentOfficer",
    label: "Compensation Officer (NH-44)",
    badge: "Compensation · 30%",
    email: "compensation@landacquisition.gov.in",
    password: "Compensation@2026!",
    departmentName: "Compensation",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "Coins",
    color: "from-amber-600 to-orange-700",
    pillBg: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    projectCode: "NH44-P2-2026",
    projectName: "NH-44 Highway Expansion",
    role: "DepartmentOfficer",
    label: "Rehabilitation Officer (NH-44)",
    badge: "Rehab · 25%",
    email: "rehabilitation@landacquisition.gov.in",
    password: "Rehab@2026Support!",
    departmentName: "Rehabilitation",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "Home",
    color: "from-pink-600 to-rose-700",
    pillBg: "bg-pink-50 text-pink-700 border-pink-200",
  },
  {
    projectCode: "NH44-P2-2026",
    projectName: "NH-44 Highway Expansion",
    role: "DepartmentOfficer",
    label: "Approvals Officer (NH-44)",
    badge: "Approvals · 5%",
    email: "approvals@landacquisition.gov.in",
    password: "Approvals@2026!",
    departmentName: "Approvals",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "FileCheck",
    color: "from-teal-600 to-emerald-700",
    pillBg: "bg-teal-50 text-teal-700 border-teal-200",
  },
  {
    projectCode: "NH44-P2-2026",
    projectName: "NH-44 Highway Expansion",
    role: "DepartmentOfficer",
    label: "Possession Officer (NH-44)",
    badge: "Possession · 10%",
    email: "possession@landacquisition.gov.in",
    password: "Possession@2026!",
    departmentName: "Possession",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "Flag",
    color: "from-indigo-600 to-violet-700",
    pillBg: "bg-indigo-50 text-indigo-700 border-indigo-200",
  },

  // ── Project 2: Eastern Freight Corridor (Bihar) ──
  {
    projectCode: "EFC-LP-2026",
    projectName: "Eastern Freight Corridor",
    role: "DepartmentOfficer",
    label: "Survey Lead (EFC Corridor)",
    badge: "Survey · 15%",
    email: "survey.efc@landacquisition.gov.in",
    password: "Survey@2026Efc!",
    departmentName: "Survey",
    defaultProjectCode: "EFC-LP-2026",
    requiresProject: true,
    icon: "MapPin",
    color: "from-emerald-600 to-teal-700",
    pillBg: "bg-emerald-50 text-emerald-700 border-emerald-200",
  },
  {
    projectCode: "EFC-LP-2026",
    projectName: "Eastern Freight Corridor",
    role: "DepartmentOfficer",
    label: "Legal Lead (EFC Corridor)",
    badge: "Legal · 15%",
    email: "legal.efc@landacquisition.gov.in",
    password: "Legal@2026Efc!",
    departmentName: "Legal Verification",
    defaultProjectCode: "EFC-LP-2026",
    requiresProject: true,
    icon: "Scale",
    color: "from-cyan-600 to-blue-700",
    pillBg: "bg-cyan-50 text-cyan-700 border-cyan-200",
  },
  {
    projectCode: "EFC-LP-2026",
    projectName: "Eastern Freight Corridor",
    role: "DepartmentOfficer",
    label: "Compensation Lead (EFC Corridor)",
    badge: "Compensation · 30%",
    email: "compensation.efc@landacquisition.gov.in",
    password: "Compensation@2026Efc!",
    departmentName: "Compensation",
    defaultProjectCode: "EFC-LP-2026",
    requiresProject: true,
    icon: "Coins",
    color: "from-amber-600 to-orange-700",
    pillBg: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    projectCode: "EFC-LP-2026",
    projectName: "Eastern Freight Corridor",
    role: "DepartmentOfficer",
    label: "Rehabilitation Lead (EFC Corridor)",
    badge: "Rehab · 25%",
    email: "rehabilitation.efc@landacquisition.gov.in",
    password: "Rehab@2026Efc!",
    departmentName: "Rehabilitation",
    defaultProjectCode: "EFC-LP-2026",
    requiresProject: true,
    icon: "Home",
    color: "from-pink-600 to-rose-700",
    pillBg: "bg-pink-50 text-pink-700 border-pink-200",
  },
  {
    projectCode: "EFC-LP-2026",
    projectName: "Eastern Freight Corridor",
    role: "DepartmentOfficer",
    label: "Clearance & NOC Lead (EFC Corridor)",
    badge: "Approvals · 5%",
    email: "approvals.efc@landacquisition.gov.in",
    password: "Approvals@2026Efc!",
    departmentName: "Approvals",
    defaultProjectCode: "EFC-LP-2026",
    requiresProject: true,
    icon: "FileCheck",
    color: "from-teal-600 to-emerald-700",
    pillBg: "bg-teal-50 text-teal-700 border-teal-200",
  },
  {
    projectCode: "EFC-LP-2026",
    projectName: "Eastern Freight Corridor",
    role: "DepartmentOfficer",
    label: "Possession Lead (EFC Corridor)",
    badge: "Possession · 10%",
    email: "possession.efc@landacquisition.gov.in",
    password: "Possession@2026Efc!",
    departmentName: "Possession",
    defaultProjectCode: "EFC-LP-2026",
    requiresProject: true,
    icon: "Flag",
    color: "from-indigo-600 to-violet-700",
    pillBg: "bg-indigo-50 text-indigo-700 border-indigo-200",
  },
];
