export const DEMO_PROJECTS = [
  {
    code: "NH44-P2-2026",
    name: "NH-44 Highway Expansion — Phase 2",
    state: "Karnataka",
    district: "Belagavi",
  },
  {
    code: "EFC-LP-2026",
    name: "Eastern Freight Corridor — Land Parcel Acquisition",
    state: "Bihar",
    district: "Patna",
  },
];

export const DEMO_ACCOUNTS = [
  {
    role: "Administrator",
    label: "System Administrator",
    badge: "Super Admin",
    email: "admin@landacquisition.gov.in",
    password: "Admin@2026Secure!",
    departmentName: "All Departments",
    icon: "ShieldAlert",
    color: "from-blue-600 to-indigo-700",
    pillBg: "bg-blue-50 text-blue-700 border-blue-200",
    desc: "Full access to national overview, all projects, creation, deletion & system settings.",
    permissions: ["all"],
    requiresProject: false,
  },
  {
    role: "SeniorOfficer",
    label: "Senior Officer",
    badge: "Executive",
    email: "senior@landacquisition.gov.in",
    password: "Senior@2026Officer!",
    departmentName: "National Oversight",
    icon: "Landmark",
    color: "from-purple-600 to-indigo-700",
    pillBg: "bg-purple-50 text-purple-700 border-purple-200",
    desc: "Executive view: GIS tracking, weighted progress, bottleneck ranking & dependency alerts.",
    permissions: ["view_all_projects", "view_analytics", "view_alerts", "export_reports"],
    requiresProject: false,
  },
  {
    role: "DepartmentOfficer",
    label: "Survey Officer",
    badge: "Stage 1 (15%)",
    email: "survey@landacquisition.gov.in",
    password: "Survey@2026Land!",
    departmentName: "Survey",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "MapPin",
    color: "from-emerald-600 to-teal-700",
    pillBg: "bg-emerald-50 text-emerald-700 border-emerald-200",
    desc: "Land demarcations, drone surveys, boundary geo-coordinates and initial notifications.",
    permissions: ["view_survey", "create_survey", "edit_survey", "add_coordinates", "upload_drone_data"],
  },
  {
    role: "DepartmentOfficer",
    label: "Legal Verification Officer",
    badge: "Stage 2 (15%)",
    email: "legal@landacquisition.gov.in",
    password: "Legal@2026Verify!",
    departmentName: "Legal Verification",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "Scale",
    color: "from-cyan-600 to-blue-700",
    pillBg: "bg-cyan-50 text-cyan-700 border-cyan-200",
    desc: "Title ownership checks, dispute hearings, encumbrance verification & NOC approvals.",
    permissions: ["view_legal", "verify_title", "check_disputes", "manage_noc", "approve_legal"],
  },
  {
    role: "DepartmentOfficer",
    label: "Compensation Officer",
    badge: "Stage 3 (30%)",
    email: "compensation@landacquisition.gov.in",
    password: "Compensation@2026!",
    departmentName: "Compensation",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "Coins",
    color: "from-amber-600 to-orange-700",
    pillBg: "bg-amber-50 text-amber-700 border-amber-200",
    desc: "Award determination, bank account verification, direct beneficiary disbursement.",
    permissions: ["view_compensation", "calculate_award", "verify_bank", "process_disbursement", "manage_beneficiaries"],
  },
  {
    role: "DepartmentOfficer",
    label: "Rehabilitation Officer",
    badge: "Stage 4 (25%)",
    email: "rehabilitation@landacquisition.gov.in",
    password: "Rehab@2026Support!",
    departmentName: "Rehabilitation",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "Home",
    color: "from-pink-600 to-rose-700",
    pillBg: "bg-pink-50 text-pink-700 border-pink-200",
    desc: "R&R schemes, resettlement plot allotment, affected families livelihood support.",
    permissions: ["view_rehabilitation", "allocate_plots", "manage_schemes", "track_livelihood", "generate_reports"],
  },
  {
    role: "DepartmentOfficer",
    label: "Approvals Officer",
    badge: "Stage 5 (5%)",
    email: "approvals@landacquisition.gov.in",
    password: "Approvals@2026!",
    departmentName: "Approvals",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "FileCheck",
    color: "from-teal-600 to-emerald-700",
    pillBg: "bg-teal-50 text-teal-700 border-teal-200",
    desc: "Environmental clearances, state gazette notifications and administrative sanctions.",
    permissions: ["view_approvals", "review_clearances", "publish_gazette", "issue_sanctions", "approve_documents"],
  },
  {
    role: "DepartmentOfficer",
    label: "Possession Officer",
    badge: "Stage 6 (10%)",
    email: "possession@landacquisition.gov.in",
    password: "Possession@2026!",
    departmentName: "Possession",
    defaultProjectCode: "NH44-P2-2026",
    requiresProject: true,
    icon: "Flag",
    color: "from-indigo-600 to-violet-700",
    pillBg: "bg-indigo-50 text-indigo-700 border-indigo-200",
    desc: "Physical land takeover, site handover to implementing agency & final completion.",
    permissions: ["view_possession", "record_takeover", "handover_site", "mark_completion", "generate_certificates"],
  },
];
